apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    svc2pod: mysql
spec:
  containers: 
  - name: mysql
    image: mysql:5.7.27
    ports: 
    - name: mysql
      containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root-pass
    - name: MYSQL_DATABASE
      value: wordpress
    - name: MYSQL_USER
      value: wordpress
    - name: MYSQL_PASSWORD
      value: wordpress-pass
